from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import logging

logger = logging.getLogger('Selenium - Scenario1')
logger.setLevel(logging.INFO)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

logger.info('Uruchamiamy przeglądarkę')
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.implicitly_wait(10)
driver.maximize_window()
logger.info('Wchodzimy na stronę www.kurs-selenium.pl/demo')
driver.get("http://www.kurs-selenium.pl/demo/")
logger.info('Klikamy w pole wyszukiwania miejsca pobytu')
driver.find_element_by_xpath("//span[text()='Search by Hotel or City Name']").click()
logger.info('Podajemy miejsce pobytu i zatwierdzamy')
driver.find_element_by_xpath("//div[@id='select2-drop']//input").send_keys('Dubai')
driver.find_element_by_xpath("//span[text()='Dubai']").click()
logger.info('Podajemy okres zamaldowania i wymeldowania')
driver.find_element_by_name("checkin").send_keys("12/09/2020")
driver.find_element_by_name("checkout").send_keys("13/09/2020")
driver.find_element_by_id("travellersInput").click()
logger.info('Podajemy typ oraz liczbę osób wybierającą się w podróż')
driver.find_element_by_id("adultInput").clear()
driver.find_element_by_id("adultInput").send_keys("4")
logger.info('Zatwierdzamy wyszukiwanie')
driver.find_element_by_xpath("//button[text()=' Search']").click()
logger.info('Zamykamy przeglądarkę')
driver.close()